### Tutorial 1 

In [1]:
# import libs 
import torch 

/home/anirudh/miniconda3/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
x = torch.empty(1)
x

tensor([596339.])

In [3]:
x = torch.empty(3)
x

tensor([1.6631e+22, 3.3734e-06, 8.4711e-07])

In [5]:
x = torch.rand(2,2)
x

tensor([[0.1257, 0.0486],
        [0.9290, 0.6481]])

In [6]:
x = torch.zeros(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [7]:
x = torch.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

#### Setting datatypes

In [8]:
x = torch.ones(2,2,dtype = int)
x

tensor([[1, 1],
        [1, 1]])

In [9]:
x.size()

torch.Size([2, 2])

#### Converting list to tensor

In [11]:
x = torch.tensor([2.5,1])
x

tensor([2.5000, 1.0000])

#### Other operations 

In [17]:
x = torch.randn(2,2)
y = torch.randn(2,2)
z = x + y
z
# this is element wise addition 

tensor([[ 1.3492,  0.3371],
        [ 1.2794, -0.4516]])

In [18]:
z = torch.add(x,y)
z

tensor([[ 1.3492,  0.3371],
        [ 1.2794, -0.4516]])

- Notice below that the value of y changes 

In [22]:
# inplace addition 
x = torch.randn(2,2)
print(x)
y = torch.randn(2,2)
print(y)
y.add_(x)
y

tensor([[ 0.5680,  0.0736],
        [-0.6091,  0.3676]])
tensor([[ 0.5618,  1.5907],
        [-0.5565, -0.7457]])


tensor([[ 1.1298,  1.6643],
        [-1.1657, -0.3781]])

#### Slicing 

In [23]:
x = torch.randn(3,5)
x

tensor([[-1.2994, -0.4728,  1.1974, -2.0597, -0.4841],
        [-1.7317, -0.1851, -0.2586, -0.3792,  2.0322],
        [ 0.1097, -1.5822,  0.2398,  0.0117, -0.0024]])

In [25]:
x[:,1:3]

tensor([[-0.4728,  1.1974],
        [-0.1851, -0.2586],
        [-1.5822,  0.2398]])

In [26]:
x[0:2,:]

tensor([[-1.2994, -0.4728,  1.1974, -2.0597, -0.4841],
        [-1.7317, -0.1851, -0.2586, -0.3792,  2.0322]])

In [29]:
# only one element tensors this can be aplpied 
x[1,1].item()

-0.18514202535152435

#### Resizing 

In [31]:
x = torch.randn(4,4)
print(x)
y = x.view(16)
print(y)

tensor([[-0.6423,  0.5736,  0.7728,  0.4152],
        [ 0.4036,  1.2466,  1.3876, -1.7189],
        [ 1.1935, -0.3972, -0.1015, -0.0394],
        [ 0.5730, -0.2595,  0.8577,  1.7796]])
tensor([-0.6423,  0.5736,  0.7728,  0.4152,  0.4036,  1.2466,  1.3876, -1.7189,
         1.1935, -0.3972, -0.1015, -0.0394,  0.5730, -0.2595,  0.8577,  1.7796])


Conversion between numpy and torch 

In [32]:
a = torch.ones(5)
print(a)
b = a.numpy()
b

tensor([1., 1., 1., 1., 1.])


array([1., 1., 1., 1., 1.], dtype=float32)

In [33]:
import numpy as np 
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


#### Note
On CPU both of them point to the same location 

In [35]:
if torch.cuda.is_available():
    print("CUDA")
else:
    print("No CUDA")

No CUDA


##### I currently dont have a GPU , so no cuda 

In [36]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device = device)
    y = torch.ones(5)
    y = y.to(device)
    z = x+y
    print(z)

##### Note 
- Numpy can only handle tensors in the CPU 

In [38]:
z = z.to("cpu")
z

tensor([[ 1.3492,  0.3371],
        [ 1.2794, -0.4516]])

#### Intro to autograd , more in next tutorial 

In [39]:
x = torch.ones(5,requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)