### Tutorial 2 : Autograd Package 

In [2]:
# import lib 
import torch 

/home/anirudh/miniconda3/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
x = torch.randn(3, requires_grad = True)
x

tensor([-0.8303,  0.8960, -0.2969], requires_grad=True)

In [4]:
y = x+2
y

tensor([1.1697, 2.8960, 1.7031], grad_fn=<AddBackward0>)

In [5]:
z = y*y*2
z = z.mean()

#### Note :
- z.backward can be implicity called only when z is a tensor

In [6]:
z.backward()
x.grad

tensor([1.5596, 3.8614, 2.2708])

#### Note 
- For situations where z is not a scalar 

In [7]:
z = y*y*2
print(z)
v = torch.tensor([0.1,1,10])
print(v)
z.backward(v)
x.grad

tensor([ 2.7364, 16.7742,  5.8011], grad_fn=<MulBackward0>)
tensor([ 0.1000,  1.0000, 10.0000])


tensor([ 2.0275, 15.4456, 70.3946])

In [8]:
# notice now y doesnt have grad function 
y = x.detach()
y

tensor([-0.8303,  0.8960, -0.2969])

In [13]:
# notice that again y doenst have gradient function , and doesnt track history 
# in our computational graph 
with torch.no_grad():
    y = x+2
    print(y)

tensor([1.1697, 2.8960, 1.7031])


In [16]:
# other method 
x.requires_grad_(False)
x

tensor([-0.8303,  0.8960, -0.2969])

#### Dummy training example 

In [18]:
weights = torch.ones(5,requires_grad= True)
print(weights)
for epoch in range(1):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
tensor([3., 3., 3., 3., 3.])


In [19]:
# notice what would happen if you increase the epochs
print(weights)
for epoch in range(2):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
tensor([6., 6., 6., 6., 6.])
tensor([9., 9., 9., 9., 9.])


#### Note 
- Upon increasing the epoch value ,the gradient keeps on changing , we have to stop this 

In [22]:
print(weights)
for epoch in range(2):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)

    weights.grad.zero_()
    

tensor([1., 1., 1., 1., 1.], requires_grad=True)
tensor([3., 3., 3., 3., 3.])
tensor([3., 3., 3., 3., 3.])
